version: "3"

services:
  postgres:
    image: postgres
    container_name: launchpads_db
    restart: unless-stopped
    ports:
      - 5432:5432
    env_file:
      - ./LaunchPad/.env
    volumes:
      - ./db/postgres_data:/var/lib/postgres

