version: "3"

services:
  postgres:
    image: postgres
    container_name: launchpads_db
    restart: unless-stopped
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: thisisasecurepassword
      POSTGRES_USER: launchpads_user
      POSTGRES_DB: launchpads_dev
    volumes:
      - ./db/postgres_data:/var/lib/postgres

