# Generated by Django 3.1.3 on 2020-11-28 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spacex', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='launchpads',
            name='id',
            field=models.CharField(max_length=24, primary_key=True, serialize=False),
        ),
    ]
